apiVersion: v1
kind: Service
metadata:
  name: doggly-nginx
  labels:
    env: dev
    service: doggly
spec:
  type: LoadBalancer
  selector:
    env: dev
    service: doggly
  ports:
    - port: 80
      targetPort: 80
