apiVersion: apps/v1
kind: Deployment
metadata:
  name: doggly-nestjs
  namespace: doggly
  labels:
    env: dev
    service: doggly
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      service: doggly
  template:
    metadata:
      labels:
        env: dev
        service: doggly
    spec:
      containers:
        - name: doggly-nginx
          image: nginx:latest
          ports:
            - containerPort: 80